name: Docker Image CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: repo.nicely.gg
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: glassbin:latest
